version: "3"
services:
  cache:
    image: redis
    container_name: smile-redis
    ports:
      - "6379:6379"

  database:
    image: mysql:latest
    container_name: smile-mysql
    ports:
        - "3306:3306"
    environment:
      - MYSQL_DATABASE=smile
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=smile
      - MYSQL_PASSWORD=secret
